/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Logica.Produtos;
import DAO.ProdutoDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author ACER
 */
public class FrCadProd extends javax.swing.JFrame {
    
    DefaultTableModel tableModel = new DefaultTableModel(null, new String[]{"Código", "Produto", "Descrição", "QTD", "Valor Unit.", "Valor Total"});
    List<Produtos> produto;
    ListSelectionModel lsmProduto;
    /**
     * Creates new form frCadProd
     */
    public FrCadProd() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        painelCadastro = new javax.swing.JPanel();
        labelCadCodigo = new javax.swing.JLabel();
        textFeildCadCodigo = new javax.swing.JTextField();
        labelCadProduto = new javax.swing.JLabel();
        textFieldCadProduto = new javax.swing.JTextField();
        labelCadQnt = new javax.swing.JLabel();
        labelCadValorUni = new javax.swing.JLabel();
        labelCadTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCadNovo = new javax.swing.JButton();
        btnCadEdita = new javax.swing.JButton();
        btnCadSalva = new javax.swing.JButton();
        btnCadExclui = new javax.swing.JButton();
        labelCadQnt1 = new javax.swing.JLabel();
        textFieldCadDesc = new javax.swing.JTextField();
        textFieldCadQnt = new javax.swing.JTextField();
        textFieldCadTotal = new javax.swing.JTextField();
        textFieldCadValUni = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaBusca = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        textFieldBusca = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Padaria");
        setResizable(false);

        painelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        labelCadCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCadCodigo.setText("Código:");

        textFeildCadCodigo.setEditable(false);
        textFeildCadCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFeildCadCodigoActionPerformed(evt);
            }
        });

        labelCadProduto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCadProduto.setText("Produto:");

        textFieldCadProduto.setEditable(false);
        textFieldCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadProdutoActionPerformed(evt);
            }
        });

        labelCadQnt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCadQnt.setText("Quantidade:");

        labelCadValorUni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCadValorUni.setText("Valor unitário:");

        labelCadTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCadTotal.setText("Total:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCadNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/novo.png"))); // NOI18N
        btnCadNovo.setText("Novo");
        btnCadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadNovoActionPerformed(evt);
            }
        });

        btnCadEdita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        btnCadEdita.setText("Editar");
        btnCadEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEditaActionPerformed(evt);
            }
        });

        btnCadSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvar.png"))); // NOI18N
        btnCadSalva.setText("Salvar");
        btnCadSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadSalvaActionPerformed(evt);
            }
        });

        btnCadExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arquivo.png"))); // NOI18N
        btnCadExclui.setText("Excluir");
        btnCadExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadExcluiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnCadEdita, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnCadSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnCadExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadEdita, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelCadQnt1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCadQnt1.setText("Descrição:");

        textFieldCadDesc.setEditable(false);
        textFieldCadDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadDescActionPerformed(evt);
            }
        });

        textFieldCadQnt.setEditable(false);
        textFieldCadQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadQntActionPerformed(evt);
            }
        });

        textFieldCadTotal.setEditable(false);
        textFieldCadTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadTotalActionPerformed(evt);
            }
        });

        textFieldCadValUni.setEditable(false);
        textFieldCadValUni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldCadValUniFocusLost(evt);
            }
        });
        textFieldCadValUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadValUniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addComponent(labelCadQnt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldCadDesc))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(labelCadCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFeildCadCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCadProduto))
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(labelCadQnt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldCadQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(labelCadValorUni)
                                .addGap(3, 3, 3)
                                .addComponent(textFieldCadValUni, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelCadTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldCadTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldCadProduto)))))
                .addContainerGap())
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadCodigo)
                    .addComponent(textFeildCadCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadProduto)
                    .addComponent(textFieldCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadQnt)
                    .addComponent(labelCadValorUni)
                    .addComponent(labelCadTotal)
                    .addComponent(textFieldCadQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCadTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCadValUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadQnt1)
                    .addComponent(textFieldCadDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        tabelaBusca.setModel(tableModel);
        tabelaBusca.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        lsmProduto = tabelaBusca.getSelectionModel();

        lsmProduto.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if(! e.getValueIsAdjusting()){
                    tabelaBuscaSelecionada(tabelaBusca);
                }
            }
        });
        jScrollPane2.setViewportView(tabelaBusca);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 102, 51))); // NOI18N

        textFieldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscaActionPerformed(evt);
            }
        });

        btnBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arquivo (1).png"))); // NOI18N
        btnBusca.setText("Pesquisar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFieldBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusca)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Sobre");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Desenvolvedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFeildCadCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFeildCadCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textFeildCadCodigoActionPerformed

    private void textFieldCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCadProdutoActionPerformed

    private void textFieldCadDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCadDescActionPerformed

    private void btnCadSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadSalvaActionPerformed
        if(!verificaVazio()){
            JOptionPane.showMessageDialog(null, "Existem campos obrigatorios em branco");
        }else{
            if(temValorNegativo()){ 
                JOptionPane.showMessageDialog(null, "Existe campos com valores negativos!");
                textFieldCadQnt.setText("");
                textFieldCadValUni.setText("");
                textFieldCadTotal.setText("");
            }else{
                try {
                    if(cacaProdutosNome()){
                        int resposta = JOptionPane.showConfirmDialog(null, "Já existe produto com esse nome!\n\nDeseja realmente salvar?", "Aviso", JOptionPane.YES_NO_OPTION);
                        if(resposta == JOptionPane.YES_OPTION){
                            salvarNoBanco();
                            limparDados();
                        }else{
                            limparDados();
                            bloqueiaCampos();
                        }
                    }else{
                        salvarNoBanco();
                        limparDados();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(FrCadProd.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } 
    }//GEN-LAST:event_btnCadSalvaActionPerformed

    private void btnCadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadNovoActionPerformed
        // TODO add your handling code here:
        verificaPreenchimento();
    }//GEN-LAST:event_btnCadNovoActionPerformed

    private void textFieldCadQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadQntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCadQntActionPerformed

    private void textFieldCadTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCadTotalActionPerformed

    private void textFieldCadValUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadValUniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCadValUniActionPerformed

    private void textFieldCadValUniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldCadValUniFocusLost
        // TODO add your handling code here:
        
        try {
            double qtd = Double.parseDouble(textFieldCadQnt.getText());
            double precoUni = Double.parseDouble(textFieldCadValUni.getText());
            //preenche o valor total com a multiplicacao do valor quantidade de valor unitario
            double total = qtd * precoUni;
            textFieldCadTotal.setText(String.format("%s", total));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite apenas numeros!");
            textFieldCadValUni.setText("");
            textFieldCadQnt.setText("");
        }
    }//GEN-LAST:event_textFieldCadValUniFocusLost

    private void textFieldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscaActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
        try{
            listarProdutos();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        } 
        
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnCadExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadExcluiActionPerformed
        if(!verificaVazio()){
            JOptionPane.showMessageDialog(null, "Existem campos obrigatorios em branco");
        }else{
            try {
                deletarDados();
                limparDados();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
        }
    }
        
        
           
    }//GEN-LAST:event_btnCadExcluiActionPerformed

    private void btnCadEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEditaActionPerformed
        if(!verificaVazio()){
            JOptionPane.showMessageDialog(null, "Existem campos obrigatorios em branco");
        }
        else if(temValorNegativo()){ 
            JOptionPane.showMessageDialog(null, "Existe campos com valores negativos!");
            limparDados();
            bloqueiaCampos();
        }
        else{
             
             try {
                 editarDados();
                 limparDados();
             }catch (SQLException e) {
                 JOptionPane.showMessageDialog(null, e);
             } 
        }
    }//GEN-LAST:event_btnCadEditaActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrSobre obj = new FrSobre();
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCadProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCadEdita;
    private javax.swing.JButton btnCadExclui;
    private javax.swing.JButton btnCadNovo;
    private javax.swing.JButton btnCadSalva;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCadCodigo;
    private javax.swing.JLabel labelCadProduto;
    private javax.swing.JLabel labelCadQnt;
    private javax.swing.JLabel labelCadQnt1;
    private javax.swing.JLabel labelCadTotal;
    private javax.swing.JLabel labelCadValorUni;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JTable tabelaBusca;
    private javax.swing.JTextField textFeildCadCodigo;
    private javax.swing.JTextField textFieldBusca;
    private javax.swing.JTextField textFieldCadDesc;
    private javax.swing.JTextField textFieldCadProduto;
    private javax.swing.JTextField textFieldCadQnt;
    private javax.swing.JTextField textFieldCadTotal;
    private javax.swing.JTextField textFieldCadValUni;
    // End of variables declaration//GEN-END:variables

    public void verificaPreenchimento(){
        if(verificaVazio()){
            int resposta = JOptionPane.showConfirmDialog(null, "Esta operação irá limpar os campos do formulário, verifique se os dados foram salvos!\n\nDeseja continuar?", "Aviso", JOptionPane.YES_NO_OPTION);
            
            if(resposta == JOptionPane.YES_OPTION){
                limparDados();
                liberaCampos();
            }
 
        }else{
            limparDados();
            liberaCampos();
        }
    }

    public void limparDados(){
        textFieldCadProduto.setText("");
        textFieldCadDesc.setText("");
        textFieldCadQnt.setText("");
        textFieldCadValUni.setText("");
        textFieldCadTotal.setText("");
        textFeildCadCodigo.setText("");
    }
    
    public void salvarNoBanco(){
        try{
            Produtos produto = new Produtos();

            produto.setNomeProd(textFieldCadProduto.getText());
            produto.setDescricao(textFieldCadDesc.getText());
            produto.setQtdeProd(textFieldCadQnt.getText());
            produto.setValUnitProd(textFieldCadValUni.getText());
            produto.setValTotalProd(textFieldCadTotal.getText());

            ProdutoDAO dao = new ProdutoDAO();
            dao.adicionar(produto);
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso");
            
            listarProdutos();
            bloqueiaCampos();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao salvar dados\n\n" + e);
        }
    }
    
    public void listarProdutos() throws SQLException{
        ProdutoDAO dao = new ProdutoDAO();
        produto = dao.getNome("%"+textFieldBusca.getText()+"%");
        exibePesquisa(produto);
    }
    
    public void exibePesquisa(List<Produtos> produto){
        while(tableModel.getRowCount()>0){
            tableModel.removeRow(0);
        }
        if(produto.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum dado encontrado");
        }else{
            String[] linha = new String[]{null, null, null, null, null, null};
            
            for(int i=0; i<produto.size(); i++){
                tableModel.addRow(linha);
                tableModel.setValueAt(produto.get(i).getIdProd(), i, 0);
                tableModel.setValueAt(produto.get(i).getNomeProd(), i, 1);
                tableModel.setValueAt(produto.get(i).getDescricao(), i, 2);
                tableModel.setValueAt(produto.get(i).getQtdeProd(), i, 3);
                tableModel.setValueAt(produto.get(i).getValUnitProd(), i, 4);
                tableModel.setValueAt(produto.get(i).getValTotalProd(), i, 5);
            }
        }
    }
    
    public void tabelaBuscaSelecionada(JTable tabela){
        if(tabelaBusca.getSelectedRow() != -1){
            textFieldCadProduto.setText(produto.get(tabela.getSelectedRow()).getNomeProd());
            textFieldCadDesc.setText(produto.get(tabela.getSelectedRow()).getDescricao());
            textFieldCadQnt.setText(produto.get(tabela.getSelectedRow()).getQtdeProd());
            textFieldCadValUni.setText(produto.get(tabela.getSelectedRow()).getValUnitProd());
            textFieldCadTotal.setText(produto.get(tabela.getSelectedRow()).getValTotalProd());
            textFeildCadCodigo.setText(Long.toString(produto.get(tabela.getSelectedRow()).getIdProd()));
            
            liberaCampos();
        }
    }
    
    public void liberaCampos(){
        textFieldCadProduto.setEditable(true);
        textFieldCadDesc.setEditable(true);
        textFieldCadQnt.setEditable(true);
        textFieldCadValUni.setEditable(true);
    }
    
    public void bloqueiaCampos(){
        textFieldCadProduto.setEditable(false);
        textFieldCadDesc.setEditable(false);
        textFieldCadQnt.setEditable(false);
        textFieldCadValUni.setEditable(false);
    }
    
    public void editarDados() throws SQLException{
        int resposta = JOptionPane.showConfirmDialog(null, "Esta operação irá atualizar valores na base de dados!\n\nDeseja continuar?", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            try{
                Produtos produto = new Produtos();

                produto.setNomeProd(textFieldCadProduto.getText());
                produto.setDescricao(textFieldCadDesc.getText());
                produto.setQtdeProd(textFieldCadQnt.getText());
                produto.setValUnitProd(textFieldCadValUni.getText());
                produto.setValTotalProd(textFieldCadTotal.getText());
                produto.setIdProd(Long.parseLong(textFeildCadCodigo.getText()));

                ProdutoDAO dao = new ProdutoDAO();
                dao.alterar(produto);
                JOptionPane.showMessageDialog(null, "Dados Atualizados com sucesso");

                listarProdutos();
                bloqueiaCampos();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Erro ao atualizar dados\n\n" + e);
            }
        }
    }
    
    public void deletarDados() throws SQLException{
        int resposta = JOptionPane.showConfirmDialog(null, "Esta operação irá remover valores na base de dados e não poderá ser desfeita!\n\nDeseja continuar?", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            try{
                Produtos produto = new Produtos();


                produto.setIdProd(Long.parseLong(textFeildCadCodigo.getText()));

                ProdutoDAO dao = new ProdutoDAO();
                dao.remover(produto);
                JOptionPane.showMessageDialog(null, "Dados removidos com sucesso");

                listarProdutos();
                bloqueiaCampos();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Erro ao remover dados\n\n" + e);
            }
        }
    }
    
    public boolean verificaVazio(){
        return (!textFieldCadProduto.getText().equals("") || !textFieldCadQnt.getText().equals("")
                || !textFieldCadValUni.getText().equals("") || !textFieldCadTotal.getText().equals("")
                || !textFieldCadDesc.getText().equals(""));
    }

    private FrSobre FrSobre() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private boolean temValorNegativo() {
        try{
            double precoUni = Double.parseDouble(textFieldCadValUni.getText());
            double  qtd = Double.parseDouble(textFieldCadQnt.getText());
            if(precoUni <0 || qtd<0) return true;
            else return false;
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Digite apenas números!");
        }
        return true;
    }
    
    public boolean cacaProdutosNome() throws SQLException{
        cacaProdutoNome();
        return qtdComNome(produto);
    }
    
    public void cacaProdutoNome() throws SQLException{
        ProdutoDAO dao = new ProdutoDAO();
        produto = dao.getNome(textFieldCadProduto.getText());
    }
    
    public boolean qtdComNome(List<Produtos> produto){
        return !produto.isEmpty();
    }
}
